services:
  - type: web
    name: contalev
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    healthCheckPath: /historico
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: SUPABASE_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_PROJECT_ID
        sync: false
